<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>preview</LangVersion>
    <WebSharperProject>Bundle</WebSharperProject>
    <WebSharperBundleOutputDir>wwwroot\js</WebSharperBundleOutputDir>
    <WebSharperRunCompiler>true</WebSharperRunCompiler>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Client.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PulseTrade.Comm.Spa.Dynamic.Renderer" Version="[0.1.0-alpha1]" />
    <PackageReference Include="WebSharper.FSharp" Version="10.1.5.674" />
    <PackageReference Include="WebSharper.UI" Version="10.1.4.674" />
  </ItemGroup>
</Project>
