<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsPackable>false</IsPackable>
    <LangVersion>preview</LangVersion>
    <WebSharperProject>spa</WebSharperProject>
    <WebSharperBundleOutputDir>wwwroot\js</WebSharperBundleOutputDir>
    <WebSharperRunCompiler>true</WebSharperRunCompiler>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Client.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PulseTrade.Comm.Spa.Dynamic.Contracts\PulseTrade.Comm.Spa.Dynamic.Contracts.fsproj" />
    <PackageReference Include="PulseTrade.Comm.Spa.Dynamic.Renderer" Version="[0.1.0-alpha27]" />
    <PackageReference Include="WebSharper.FSharp" Version="10.1.6.676" />
    <PackageReference Include="WebSharper.UI" Version="10.1.5.676" />
  </ItemGroup>
</Project>
