<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>preview</LangVersion>
    <WebSharperProject>Bundle</WebSharperProject>
    <WebSharperBundleOutputDir>wwwroot\js</WebSharperBundleOutputDir>
    <WebSharperRunCompiler>true</WebSharperRunCompiler>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Client.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="[10.1.302]" />
    <PackageReference Include="PulseTrade.Comm.Spa" Version="[0.2.5-beta117]" />
    <PackageReference Include="PulseTrade.Comm.Spa.Dynamic.Contracts" Version="[0.1.0-alpha15]" />
    <PackageReference Include="PulseTrade.Comm.Spa.Dynamic.Ptcs" Version="[0.1.0-alpha7-win54]" />
    <PackageReference Include="PulseTrade.Comm.Spa.Dynamic.Ptcs.Client" Version="[0.1.0-alpha8-win73]" />
    <PackageReference Include="WebSharper.FSharp" Version="10.1.6.676" />
    <PackageReference Include="WebSharper.UI" Version="10.1.5.676" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="$(NuGetPackageRoot)pulsetrade.comm.spa\0.2.5-beta116\contentFiles\any\any\build\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
